;;; -*- coding: utf-8; lexical-binding: t -*-

;;------------------------------------------------------------------------------
;; custom-set-faces
;;------------------------------------------------------------------------------
;; (set-face-attribute 'hoge nil :background "black" :foreground "white" ...)

(custom-set-faces
 '(default ((t (:background "black" :foreground "white"))))
 '(blue ((t (:foreground "blue"))))
 '(bold ((t (:bold t))))
 '(bold-italic ((t (:bold t :slant italic))))
 '(border ((t (:background "black"))))
 '(border-glyph ((t (nil))))
 '(buffers-tab ((t (:background "black" :foreground "white"))))
 '(calendar-today-face ((t (:underline t))))
 '(cperl-array-face ((t (:foreground "darkseagreen"))))
 '(cperl-hash-face ((t (:foreground "darkseagreen"))))
 '(cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
 '(cursor ((t (:background "yellow"))))
 '(custom-button-face ((t (nil))))
 '(custom-changed-face ((t (:background "blue" :foreground "white"))))
 '(custom-documentation-face ((t (nil))))
 '(custom-face-tag-face ((t (:underline t))))
 '(custom-group-tag-face ((t (:underline t :foreground "light blue"))))
 '(custom-group-tag-face-1 ((t (:underline t :foreground "pink"))))
 '(custom-invalid-face ((t (:background "red" :foreground "yellow"))))
 '(custom-modified-face ((t (:background "blue" :foreground "white"))))
 '(custom-rogue-face ((t (:background "black" :foreground "pink"))))
 '(custom-saved-face ((t (:underline t))))
 '(custom-set-face ((t (:background "white" :foreground "blue"))))
 '(custom-state-face ((t (:foreground "lime green"))))
 '(custom-variable-button-face ((t (:underline t :bold t))))
 '(custom-variable-tag-face ((t (:underline t :foreground "light blue"))))
 '(diary-face ((t (:foreground "IndianRed"))))
 '(erc-action-face ((t (:bold t))))
 '(erc-bold-face ((t (:bold t))))
 '(erc-default-face ((t (nil))))
 '(erc-direct-msg-face ((t (:foreground "sandybrown"))))
 '(erc-error-face ((t (:bold t :foreground "IndianRed"))))
 '(erc-input-face ((t (:foreground "Beige"))))
 '(erc-inverse-face ((t (:background "wheat" :foreground "darkslategrey"))))
 '(erc-notice-face ((t (:foreground "MediumAquamarine"))))
 '(erc-pal-face ((t (:foreground "palegreen"))))
 '(erc-prompt-face ((t (:foreground "MediumAquamarine"))))
 '(erc-underline-face ((t (:underline t))))
 '(eshell-ls-archive-face ((t (:bold t :foreground "IndianRed"))))
 '(eshell-ls-backup-face ((t (:foreground "Grey"))))
 '(eshell-ls-clutter-face ((t (:foreground "DimGray"))))
 '(eshell-ls-directory-face ((t (:bold t :foreground "MediumSlateBlue"))))
 '(eshell-ls-executable-face ((t (:foreground "Coral"))))
 '(eshell-ls-missing-face ((t (:foreground "black"))))
 '(eshell-ls-picture-face ((t (:foreground "Violet"))))
 '(eshell-ls-product-face ((t (:foreground "sandybrown"))))
 '(eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
 '(eshell-ls-special-face ((t (:foreground "Gold"))))
 '(eshell-ls-symlink-face ((t (:foreground "White"))))
 '(eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
 '(eshell-prompt-face ((t (:foreground "MediumAquamarine"))))
 '(fl-comment-face ((t (:foreground "gold"))))
 '(fl-doc-string-face ((t (:foreground "purple"))))
 '(fl-function-name-face ((t (:foreground "red"))))
 '(fl-keyword-face ((t (:foreground "cadetblue"))))
 '(fl-string-face ((t (:foreground "green"))))
 '(fl-type-face ((t (:foreground "yellow"))))
 '(font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
 '(font-lock-comment-face ((t (:foreground "gold"))))
 '(font-lock-constant-face ((t (:foreground "Aquamarine"))))
 '(font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
 '(font-lock-function-name-face ((t (:foreground "YellowGreen"))))
 '(font-lock-keyword-face ((t (:foreground "light Yellow"))))
 '(font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
 '(font-lock-reference-face ((t (:foreground "SlateBlue"))))
 '(font-lock-string-face ((t (:foreground "Orange"))))
 '(font-lock-type-face ((t (:foreground "Green"))))
 '(font-lock-variable-name-face ((t (:foreground "darkseagreen"))))
 '(font-lock-warning-face ((t (:bold t :foreground "Pink"))))
 '(gnus-cite-attribution-face ((t (nil))))
 '(gnus-cite-face-1 ((t (:bold t :foreground "deep sky blue"))))
 '(gnus-cite-face-10 ((t (:foreground "medium purple"))))
 '(gnus-cite-face-11 ((t (:foreground "turquoise"))))
 '(gnus-cite-face-2 ((t (:bold t :foreground "cadetblue"))))
 '(gnus-cite-face-3 ((t (:bold t :foreground "gold"))))
 '(gnus-cite-face-4 ((t (:foreground "light pink"))))
 '(gnus-cite-face-5 ((t (:foreground "pale green"))))
 '(gnus-cite-face-6 ((t (:bold t :foreground "chocolate"))))
 '(gnus-cite-face-7 ((t (:foreground "orange"))))
 '(gnus-cite-face-8 ((t (:foreground "magenta"))))
 '(gnus-cite-face-9 ((t (:foreground "violet"))))
 '(gnus-emphasis-bold ((t (:bold t))))
 '(gnus-emphasis-bold-italic ((t (:slant italic :bold t))))
 '(gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
 '(gnus-emphasis-italic ((t (:slant italic))))
 '(gnus-emphasis-underline ((t (:underline t))))
 '(gnus-emphasis-underline-bold ((t (:underline t :bold t))))
 '(gnus-emphasis-underline-bold-italic ((t (:slant italic :underline t :bold t))))
 '(gnus-emphasis-underline-italic ((t (:slant italic :underline t))))
 '(gnus-group-mail-1-empty-face ((t (:foreground "aquamarine1"))) t)
 '(gnus-group-mail-1-face ((t (:bold t :foreground "aquamarine1"))) t)
 '(gnus-group-mail-2-empty-face ((t (:foreground "aquamarine2"))) t)
 '(gnus-group-mail-2-face ((t (:bold t :foreground "aquamarine2"))) t)
 '(gnus-group-mail-3-empty-face ((t (:foreground "aquamarine3"))) t)
 '(gnus-group-mail-3-face ((t (:bold t :foreground "aquamarine3"))) t)
 '(gnus-group-mail-low-empty-face ((t (:foreground "aquamarine4"))) t)
 '(gnus-group-mail-low-face ((t (:bold t :foreground "aquamarine4"))) t)
 '(gnus-group-news-1-empty-face ((t (:foreground "PaleTurquoise"))) t)
 '(gnus-group-news-1-face ((t (:bold t :foreground "PaleTurquoise"))) t)
 '(gnus-group-news-2-empty-face ((t (:foreground "turquoise"))) t)
 '(gnus-group-news-2-face ((t (:bold t :foreground "turquoise"))) t)
 '(gnus-group-news-3-empty-face ((t (nil))) t)
 '(gnus-group-news-3-face ((t (:bold t))) t)
 '(gnus-group-news-4-empty-face ((t (nil))) t)
 '(gnus-group-news-4-face ((t (:bold t))) t)
 '(gnus-group-news-5-empty-face ((t (nil))) t)
 '(gnus-group-news-5-face ((t (:bold t))) t)
 '(gnus-group-news-6-empty-face ((t (nil))) t)
 '(gnus-group-news-6-face ((t (:bold t))) t)
 '(gnus-group-news-low-empty-face ((t (:foreground "DarkTurquoise"))) t)
 '(gnus-group-news-low-face ((t (:bold t :foreground "DarkTurquoise"))) t)
 '(gnus-header-content-face ((t (:foreground "forest green"))))
 '(gnus-header-from-face ((t (:bold t :foreground "spring green"))))
 '(gnus-header-name-face ((t (:foreground "deep sky blue"))))
 '(gnus-header-newsgroups-face ((t (:bold t :foreground "purple"))))
 '(gnus-header-subject-face ((t (:bold t :foreground "orange"))))
 '(gnus-signature-face ((t (:bold nil :foreground "khaki"))))
 '(gnus-splash-face ((t (:foreground "Brown"))) t)
 '(gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))) t)
 '(gnus-summary-high-ancient-face ((t (:bold nil :foreground "SkyBlue"))) t)
 '(gnus-summary-high-read-face ((t (:bold nil :foreground "PaleGreen"))) t)
 '(gnus-summary-high-ticked-face ((t (:bold nil :foreground "pink"))) t)
 '(gnus-summary-high-unread-face ((t (:bold nil))) t)
 '(gnus-summary-low-ancient-face ((t (:foreground "SkyBlue"))) t)
 '(gnus-summary-low-read-face ((t (:foreground "PaleGreen"))) t)
 '(gnus-summary-low-ticked-face ((t (:foreground "pink"))) t)
 '(gnus-summary-low-unread-face ((t (nil))) t)
 '(gnus-summary-normal-ancient-face ((t (:foreground "SkyBlue"))) t)
 '(gnus-summary-normal-read-face ((t (:foreground "PaleGreen"))) t)
 '(gnus-summary-normal-ticked-face ((t (:foreground "pink"))) t)
 '(gnus-summary-normal-unread-face ((t (nil))) t)
 '(gnus-summary-selected-face ((t (:underline t))) t)
 '(green ((t (:foreground "green"))))
 '(gui-button-face ((t (:background "grey75" :foreground "black"))))
 '(gui-element ((t (:background "#D4D0C8" :foreground "black"))))
 '(highlight ((t (:background "darkolivegreen"))))
 '(highline-face ((t (:background "SeaGreen"))))
 '(holiday-face ((t (:background "DimGray"))))
 '(info-menu-5 ((t (:underline t))))
 '(info-node ((t (:underline t :bold t :foreground "DodgerBlue1"))))
 '(info-xref ((t (:underline t :foreground "DodgerBlue1"))))
 '(isearch ((t (:background "blue"))))
 '(isearch-secondary ((t (:foreground "red3"))))
 '(italic ((t (:slant italic))))
 '(left-margin ((t (nil))))
 '(list-mode-item-selected ((t (:background "gray68" :foreground "white"))))
 '(message-cited-text-face ((t (:bold t :foreground "green"))) t)
 '(message-header-cc-face ((t (:bold t :foreground "green4"))) t)
 '(message-header-name-face ((t (:bold t :foreground "orange"))) t)
 '(message-header-newsgroups-face ((t (:bold t :foreground "violet"))) t)
 '(message-header-other-face ((t (:bold t :foreground "chocolate"))) t)
 '(message-header-subject-face ((t (:bold t :foreground "yellow"))) t)
 '(message-header-to-face ((t (:bold t :foreground "cadetblue"))) t)
 '(message-header-xheader-face ((t (:bold t :foreground "light blue"))) t)
 '(message-mml-face ((t (:bold t :foreground "Green3"))) t)
 '(message-separator-face ((t (:foreground "blue3"))) t)
 '(mode-line ((t (:background "DarkRed" :foreground "white" :box (:line-width -1 :style released-button)))))
 '(p4-depot-added-face ((t (:foreground "blue"))))
 '(p4-depot-deleted-face ((t (:foreground "red"))))
 '(p4-depot-unmapped-face ((t (:foreground "grey30"))))
 '(p4-diff-change-face ((t (:foreground "dark green"))))
 '(p4-diff-del-face ((t (:foreground "red"))))
 '(p4-diff-file-face ((t (:background "gray90"))))
 '(p4-diff-head-face ((t (:background "gray95"))))
 '(p4-diff-ins-face ((t (:foreground "blue"))))
 '(pointer ((t (nil))))
 '(primary-selection ((t (:background "blue"))))
 '(qt-classes-face ((t (:foreground "Red"))))
 '(red ((t (:foreground "red"))))
 '(region ((t (:background "blue"))))
 '(right-margin ((t (nil))))
 '(secondary-selection ((t (:background "darkslateblue"))))
 '(show-paren-match-face ((t (:background "Aquamarine" :foreground "SlateBlue"))) t)
 '(show-paren-mismatch-face ((t (:background "Red" :foreground "White"))) t)
 '(text-cursor ((t (:background "yellow" :foreground "black"))))
 '(toolbar ((t (nil))))
 '(underline ((nil (:underline nil))))
 '(vertical-divider ((t (nil))))
 '(widget ((t (nil))))
 '(widget-button-face ((t (:bold t))) t)
 '(widget-button-pressed-face ((t (:foreground "red"))) t)
 '(widget-documentation-face ((t (:foreground "lime green"))) t)
 '(widget-field-face ((t (:background "dim gray"))) t)
 '(widget-inactive-face ((t (:foreground "light gray"))) t)
 '(widget-single-line-field-face ((t (:background "dim gray"))) t)
 '(woman-bold-face ((t (:bold t :foreground "yellow"))) t)
 '(woman-italic-face ((t (:slant italic :foreground "cyan"))) t)
 '(woman-unknown-face ((t (:foreground "LightSalmon"))) t)
 '(yellow ((t (:foreground "yellow"))))
 '(zmacs-region ((t (:background "snow" :foreground "blue"))))
 )
